name: Bruce Desktop App

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build native distributions
        run: ./gradlew clean package

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: desktop-binaries
          path: |
            composeApp/build/compose/binaries/main/app/bruce.app/bin/*
          if-no-files-found: error
