name: Bruce Desktop App

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Clean and Build
        run: ./gradlew clean build

      - name: Check path
        run: ls -alh

      - name: Find Builds
        run: find . -name "*jar"

      - name: Find executables
        run: find . -perm -700 -type f

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: build/libs/*.jar
