name: Release BruceApp Build

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 34
        build-tools: 34.0.0

    - name: Accept licenses
      run: |
        yes | sdkmanager --licenses || true

    - name: Build release APK
      run: |
        ./gradlew clean assembleRelease

    - name: Verify APK exists
      id: verify-apk
      run: |
        APK_PATH="composeApp/build/outputs/apk/release/composeApp-release.apk"
        if [ ! -f "$APK_PATH" ]; then
          echo "ERROR: APK not found at $APK_PATH"
          find . -name '*.apk' || true
          exit 1
        fi
        echo "APK exists at: $APK_PATH"
        echo "apk_path=$APK_PATH" >> $GITHUB_OUTPUT

    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ${{ steps.verify-apk.outputs.apk_path }}
        draft: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
