name: Bruce iOS Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Use gradle to setup xcode files
      run: ./gradlew :iosApp:assembleDebug

    - name: Set up CocoaPods
      run: |
        cd iosApp
        pod init
        echo "platform :ios, '14.0'" > Podfile
        echo "target 'iosApp' do" >> Podfile
        echo "  use_frameworks!" >> Podfile
        echo "end" >> Podfile
        pod install --repo-update

    - name: Build with Gradle
      run: ./gradlew clean build

