name: Bruce iOS Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Create Podfile
      run: |
        echo "platform :ios, '14.0'" > Podfile
        echo "target 'BruceApp' do" >> Podfile
        echo "  use_frameworks!" >> Podfile
        echo "end" >> Podfile

    - name: Install dependencies
      run: |
        brew reinstall cocoapods
        pod install

    - name: Build with Gradle
      run: ./gradlew clean build
